# Check every day at 11:10am Adelaide/Australia for updated ABS data

name: GET
on:
  pull_request



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-data:
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install packages
        run: |
          install.packages('httr')
      - name: Set header
        run: |
          header = c('user-agent' = 'Labour market data access [hamish.gamble@flinders.edu.au])

      - name: Get data
        run: |
          dl = httr::GET(url = 'https://www.jobsandskills.gov.au/sites/default/files/2022-11/IVI_DATA_regional%20-%20May%202010%20onwards.xlsx', header = httr::add_headers(header), httr::write_disk(here::here('data-raw/ivi_regional.xlsx'), overwrite = TRUE))"
        
      - name: Print 
        run: |
          dl


