# Check every day at 11:10am Adelaide/Australia for updated ABS data

name: GET
on:
  pull_request



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-data:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Install packages
        run: |
          install.packages('httr')
          install.packages('here')
          install.packages('readxl')
      - name: GET
        run: |
          header = c('Connection' = 'keep-alive', 'user-agent' = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36')
          dl = httr::GET(url = 'https://www.jobsandskills.gov.au/sites/default/files/2022-11/IVI_DATA_regional%20-%20May%202010%20onwards.xlsx', header = httr::add_headers(header), httr::write_disk(here::here('data-raw/ivi_regional.xlsx'), overwrite = TRUE))
          dl
          file.exists(here::here('data-raw/ivi_regional.xlsx'))
          readxl::read_excel(here::here('data-raw/ivi_regional.xlsx'))
        shell: Rscript {0}


