name: update-data

# Controls when the action will run. Run this job every weekday at 12:40am UTC, which should be 11:10am Adelaide time
on:
   schedule:
      - cron: '35 0 * * 1-5'

   push:
    branches:
      - cleanup

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
        GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: renv
      - uses: r-lib/actions/setup-renv@v2
          
      - name: Update data
        run: |
          Rscript -e "source('data-raw/update_abs')"
      - name: Commit new data
        run: |
          git config --global user.name 'Hamish Gamble'
          git config --global user.email 'gamb0043@flinders.edu.au'
          git add .
          git commit -m 'Scheduled data updates' || echo "No changes to commit"
          git push || echo "No changes to commit"

