# Check every day at 11:10am Adelaide/Australia for updated ABS data

name: update-abs

# Controls when the action will run. Run this job every weekday at 12:40am UTC, which should be 11:10am Adelaide time
on:
   schedule:
      - cron: '35 0 * * 1-5'

   push:
    branches:
      - master
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
        GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libharfbuzz-dev libfribidi-dev 
          sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 

      - uses: r-lib/actions/setup-renv@v2

      - name: Get data
        run: |
          Rscript -e "library(aitidata)"
          Rscript -e "aitidata:::update_abs()"
          Rscript -e "devtools::document()"
      - name: Render README
        run: |
          Rscript -e "rmarkdown::render(here::here('README.Rmd'))"
      - name: Commit
        run: |
          git config --global user.name 'Hamish Gamble'
          git config --global user.email 'gamb0043@flinders.edu.au'
          git add .
          git commit -m 'Scheduled data updates' || echo "No changes to commit"
          git push || echo "No changes to commit"

